
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tutti_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tutti_test
  pool: 5
  username:
  password:
